# Herda da nossa imagem base com todas as dependências e o código compartilhado
FROM saka-base:latest

# Copia apenas o ponto de entrada específico deste agente
COPY --chown=sakauser:sakauser main.py .