# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Define o diretório de trabalho principal
WORKDIR /app

# Copia todo o código do projeto para o diretório de trabalho
# O .dockerignore deve ser usado para excluir arquivos desnecessários (ex: .git)
COPY . /app

# Define o PYTHONPATH para incluir a raiz do projeto, permitindo imports absolutos
ENV PYTHONPATH "${PYTHONPATH}:/app"

# Argumento para o caminho do arquivo de dependências específico do agente
ARG REQUIREMENTS_PATH
# Instala as dependências do agente
RUN pip install --no-cache-dir -r ${REQUIREMENTS_PATH}

# Argumento para o diretório de trabalho do agente
ARG AGENT_WORKDIR
# Define o diretório de trabalho final para o do agente
WORKDIR ${AGENT_WORKDIR}

# Expõe a porta e executa o Uvicorn
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]